const vi = {
  sessionSelector: {
    label: 'Buổi diễn *',
    empty: 'Không có đêm diễn nào',
    live: '🔴 Đang diễn – ',
    planned: '📅 ',
  },
  sheetPanel: {
    title: 'Màn Hình Sheet Nhạc',
    addBtn: '+',
    fullscreenBtn: '🔲',
    noSong: 'Chưa chọn bài hát',
    selectHint: 'Chọn sheet bên trên',
    addModalTitle: 'Thêm sheet nhạc',
    urlPlaceholder: 'Google Drive URL của sheet nhạc...',
    toneMalePlaceholder: 'Tone Nam (vd: C)',
    toneFemalePlaceholder: 'Tone Nữ (vd: A)',
    savingBtn: 'Đang lưu...',
    saveBtn: '+',
    verifyBtn: '✓',
    deleteBtn: '🗑',
    cancelBtn: 'Hủy',
    confirmDeleteTitle: 'Xác nhận xóa',
    confirmDeleteMsg: 'Bạn có chắc muốn xóa sheet này không? Hành động này không thể hoàn tác.',
    errCannotAdd: 'Không thể thêm sheet',
    errPickerNotConfigured: 'Google API key / Client ID chưa được cấu hình',
    errPickerAuth: 'Không thể xác thực Google',
    errPickerFailed: 'Không thể mở Drive picker',
    fullscreenTitle: 'Sheet Nhạc',
  },
  lyricPanel: {
    title: 'Màn Hình Lời Bài Hát',
    addBtn: '+ Thêm lời',
    fullscreenBtn: '🔲',
    noSong: 'Chưa chọn bài hát',
    selectHint: 'Chọn lời bên trên',
    presentTitle: 'Hiển thị cho người hát',
    editBtn: '✏️',
    exitEditBtn: '✕',
    openTabBtn: '↗',
    verifyBtn: '✓',
    deleteBtn: '🗑',
    addModalTitle: 'Thêm lời bài hát',
    textPlaceholder: 'Nhập lời bài hát...',
    yearPlaceholder: 'Năm sáng tác (vd: 2003)',
    aiBadge: 'Từ AI',
    aiFetchBtn: '🤖 Lấy từ AI',
    aiFetchingBtn: 'Đang lấy...',
    saveBtn: '💾 Lưu lời',
    savingBtn: 'Đang lưu...',
    generateSlideBtn: '✨ Tạo Slide Lyric',
    generatingSlideBtn: 'Đang tạo...',
    viewSlideLink: '📊 Xem slide',
    cancelBtn: 'Hủy',
    closeBtn: 'Đóng',
    confirmDeleteTitle: 'Xác nhận xóa',
    confirmDeleteMsg: 'Bạn có chắc muốn xóa lời này không? Hành động này không thể hoàn tác.',
    errCannotSave: 'Không thể lưu lời',
    errAiNotImpl: 'Chức năng AI chưa được tích hợp',
    errAiFailed: 'Không thể lấy lời từ AI',
    errSlideNotImpl: 'Chức năng tạo slide chưa được tích hợp',
    errSlideFailed: 'Không thể tạo slide',
    fullscreenTitle: 'Lời Bài Hát',
  },
  songsPage: {
    title: 'Quản Lý Bài Hát',
  },
  editSongPage: {
    title: 'Chỉnh sửa bài hát',
    backBtn: '← Quay lại',
    doneBtn: 'Hoàn tất',
    loadingMsg: 'Đang tải...',
  },
  songBanner: {
    titleLabel: 'Tên bài hát',
    titlePlaceholder: 'Nhập tên bài hát...',
    authorLabel: 'Nhạc sỹ',
    authorPlaceholder: 'Tên nhạc sỹ (tuỳ chọn)...',
    errCannotSave: 'Không thể lưu thay đổi',
  },
  createSong: {
    modalTitle: 'Thêm bài hát mới',
    titleLabel: 'Tên bài hát',
    titlePlaceholder: 'Nhập tên bài hát...',
    authorLabel: 'Nhạc sỹ',
    authorPlaceholder: 'Tên nhạc sỹ (tuỳ chọn)...',
    createBtn: 'Tạo bài hát',
    creatingBtn: 'Đang tạo...',
    cancelBtn: 'Hủy',
    errCannotCreate: 'Không thể tạo bài hát',
  },
  fullscreen: {
    closeBtn: '✖ Đóng',
  },
} as const;

export default vi;